Develop
kasisaki/go-db-sql-final pull request #1
Opened 2024-02-05 06:15 UTC by kasisaki

First try

2024-02-05 12:31 UTC, robotomize requested changes
Все отлично, хорошая работа, все кейсы есть, все ок. Единственное нужно поправить кейс с rows.Err(), остальные комменты опциональны

2024-02-05 12:31 UTC, robotomize commented on parcel.go
> +		log.Print("Error adding a new parcel into DB")
Логировать лчше на верхнем уровне. То есть в нашем случае в main.go или в тестах

2024-02-05 12:31 UTC, robotomize commented on parcel.go
> +	err := row.Scan(&p.Number, &p.Client, &p.Status, &p.Address, &p.CreatedAt)
Да, отлично

2024-02-05 12:31 UTC, robotomize commented on parcel.go
> +	}
Нужно обработать еще rows.Err() после вашего цикла получения набора строк

2024-02-05 12:31 UTC, robotomize commented on parcel.go
> +	if isRegistered {
Тут с точки зрения лаконичности я бы избавился от else, например 
```go
if registered {
  _, err := s.db.Exec("UPDATE parcel SET address = :address WHERE number = :number",
	sql.Named("address", address),
	sql.Named("number", number))
  return nil
}
return errors.New("parcel is not registered")
```

2024-02-05 12:31 UTC, robotomize commented on parcel.go
> +		_, err := s.db.Exec("DELETE FROM parcel WHERE number = :number",
Еще можно в целом сделать удаление объекта, если статус registered прям в запросе это проверить

2024-02-05 12:31 UTC, robotomize commented on parcel.go
> +func checkParcelIsRegistered(number int, db *sql.DB) (bool, error) {
Круто, что вынесли в отдельный обработчик

2024-02-05 12:31 UTC, robotomize commented on parcel_test.go
> +	require.Equal(t, parcelFromDb2, *new(Parcel))
Тут уже можно не проверять в целом, так как если возвращается ошибка, с точки зрения практик на Go мы можем на первое значение даже не смотреть а обработать ошибку

2024-02-05 22:18 UTC, kasisaki commented on parcel.go
> +		log.Print("Error adding a new parcel into DB")
Спасибо за комментарии. Имеется ввиду логирование желательно на более высоком уровне делать, если функция возвращает возникшую ошибку или вне зависимости от ретерна?

2024-02-05 22:56 UTC, kasisaki commented on parcel.go
> +		_, err := s.db.Exec("DELETE FROM parcel WHERE number = :number",
Я об этом думал, но решил, что мне хотелось бы понять каким именно образом и по какой причине завершился вызов функции, поэтому разделил на два запроса. 

> Еще можно в целом сделать удаление объекта, если статус registered прям в запросе это проверить

2024-02-05 22:57 UTC, kasisaki commented on parcel.go
> +		log.Print("Error adding a new parcel into DB")
> Логировать лчше на верхнем уровне. То есть в нашем случае в main.go или в тестах

Спасибо за комментарии. Имеется ввиду логирование желательно на более высоком уровне делать, если функция возвращает возникшую ошибку или вне зависимости от ретерна?

2024-02-05 22:58 UTC, kasisaki commented on parcel.go
> +	if isRegistered {
Согласен. Поменял.

2024-02-06 06:35 UTC, robotomize approved these changes
Отличная работа, принято!

2024-05-21 17:51 UTC, merged